KOALA_WIFI_MANAGER_VERSION = 1.0
KOALA_WIFI_MANAGER_SITE = package/koala-wifi-manager/src
KOALA_WIFI_MANAGER_SITE_METHOD = local
KOALA_WIFI_MANAGER_LICENSE = GPL-2.0
KOALA_WIFI_BLE_LICENSE_FILES = LICENSE

KOALA_WIFI_MANAGER_INSTALL_TARGET = YES
KOALA_WIFI_MANAGER_DEPENDENCIES = koala-dlt koala-capicxx-someip-runtime

KOALA_WIFI_MANAGER_CONF_OPTS +=	-DCommonAPI_DIR=$(STAGING_DIR)/usr \
								-DCMAKE_PREFIX_PATH=$(STAGING_DIR)/usr \
								-DUSE_DLT=1

$(eval $(cmake-package))
