KOALA_LVGL_APP_VERSION = 1.0
KOALA_LVGL_APP_SITE = package/koala-lvgl-app/src
KOALA_LVGL_APP_SITE_METHOD = local
KOALA_LVGL_APP_LICENSE = GPL-2.0
KOALA_LVGL_APP_LICENSE_FILES = LICENSE

KOALA_LVGL_APP_INSTALL_TARGET = YES

KOALA_LVGL_APP_CONF_OPTS += -DCMAKE_PREFIX_PATH=$(STAGING_DIR)/usr \
							-DLV_USE_DEMO_WIDGETS=1

$(eval $(cmake-package))
