KOALA_LVGL_APP_VERSION = 1.0
KOALA_LVGL_APP_SITE = package/koala-lvgl-app/src
KOALA_LVGL_APP_SITE_METHOD = local
KOALA_LVGL_APP_LICENSE = GPL-2.0
KOALA_LVGL_APP_LICENSE_FILES = LICENSE

$(eval $(cmake-package))
