KOALA_CAPICXX_CORE_RUNTIME_VERSION = 3.2.4
KOALA_CAPICXX_CORE_RUNTIME_SITE = $(call github,COVESA,capicxx-core-runtime,$(KOALA_CAPICXX_CORE_RUNTIME_VERSION))
KOALA_CAPICXX_CORE_RUNTIME_LICENSE = MIT
KOALA_CAPICXX_CORE_RUNTIME_LICENSE_FILES = LICENSE
KOALA_CAPICXX_CORE_RUNTIME_INSTALL_STAGING = YES
KOALA_CAPICXX_CORE_RUNTIME_INSTALL_TARGET = YES

#KOALA_CAPICXX_CORE_RUNTIME_CONF_OPTS += -DCMAKE_PREFIX_PATH=$(STAGING_DIR)/usr

# Invoke the CMake package handling
$(eval $(cmake-package))
