/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_KOALA_Koala_Wifi_Ble_PROXY_HPP_
#define V1_COM_KOALA_Koala_Wifi_Ble_PROXY_HPP_

#include <v1/com/koala/KoalaWifiBleProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace koala {

template <typename ... _AttributeExtensions>
class KoalaWifiBleProxy
    : virtual public KoalaWifiBle,
      virtual public KoalaWifiBleProxyBase,
      virtual public _AttributeExtensions... {
public:
    KoalaWifiBleProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~KoalaWifiBleProxy();

    typedef ::v1::com::koala::KoalaWifiBle InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls turn_on_wifi with synchronous semantics.
     *
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void turn_on_wifi(CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls turn_on_wifi with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> turn_on_wifiAsync(Turn_on_wifiAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);



 private:
    std::shared_ptr< KoalaWifiBleProxyBase> delegate_;
};

typedef KoalaWifiBleProxy<> KoalaWifiBleProxyDefault;


//
// KoalaWifiBleProxy Implementation
//
template <typename ... _AttributeExtensions>
KoalaWifiBleProxy<_AttributeExtensions...>::KoalaWifiBleProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< KoalaWifiBleProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< KoalaWifiBleProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
KoalaWifiBleProxy<_AttributeExtensions...>::~KoalaWifiBleProxy() {
}

template <typename ... _AttributeExtensions>
void KoalaWifiBleProxy<_AttributeExtensions...>::turn_on_wifi(CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    delegate_->turn_on_wifi(_internalCallStatus, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> KoalaWifiBleProxy<_AttributeExtensions...>::turn_on_wifiAsync(Turn_on_wifiAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->turn_on_wifiAsync(_callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &KoalaWifiBleProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool KoalaWifiBleProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool KoalaWifiBleProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& KoalaWifiBleProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& KoalaWifiBleProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> KoalaWifiBleProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace koala
} // namespace com
} // namespace v1



// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_KOALA_Koala_Wifi_Ble_PROXY_HPP_
