/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COM_KOALA_KOALA_WIFI_BLE_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COM_KOALA_KOALA_WIFI_BLE_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/com/koala/KoalaWifiBleStub.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace koala {

template <typename _Stub = ::v1::com::koala::KoalaWifiBleStub, typename... _Stubs>
class KoalaWifiBleSomeIPStubAdapterInternal
    : public virtual KoalaWifiBleStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< KoalaWifiBleSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> KoalaWifiBleSomeIPStubAdapterHelper;

    ~KoalaWifiBleSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        KoalaWifiBleSomeIPStubAdapterHelper::deinit();
    }

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::com::koala::KoalaWifiBleStub,
        CommonAPI::Version
    > getKoalaWifiBleInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::com::koala::KoalaWifiBleStub,
        std::tuple< >,
        std::tuple< >,
        std::tuple< >,
        std::tuple< >
    > turn_on_wifiStubDispatcher;
    
    KoalaWifiBleSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        KoalaWifiBleSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< KoalaWifiBleStub>(_stub)),
        getKoalaWifiBleInterfaceVersionStubDispatcher(&KoalaWifiBleStub::lockInterfaceVersionAttribute, &KoalaWifiBleStub::getInterfaceVersion, false, true),
        turn_on_wifiStubDispatcher(
            &KoalaWifiBleStub::turn_on_wifi,
            false,
            _stub->hasElement(0),
            std::make_tuple(),
            std::make_tuple())
        
    {
        KoalaWifiBleSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x3e8) }, &turn_on_wifiStubDispatcher );
        // Provided events/fields
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};


template <typename _Stub, typename... _Stubs>
void KoalaWifiBleSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void KoalaWifiBleSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v1::com::koala::KoalaWifiBleStub, typename... _Stubs>
class KoalaWifiBleSomeIPStubAdapter
    : public KoalaWifiBleSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    KoalaWifiBleSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          KoalaWifiBleSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace koala
} // namespace com
} // namespace v1

#endif // V1_COM_KOALA_Koala_Wifi_Ble_SOMEIP_STUB_ADAPTER_HPP_
