/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_KOALA_Wifi_Manager_STUB_HPP_
#define V1_COM_KOALA_Wifi_Manager_STUB_HPP_

#include <functional>
#include <sstream>



#include <v1/com/koala/WifiManagerDataTypes.hpp>

#include <v1/com/koala/WifiManager.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <cstdint>
#include <vector>

#include <mutex>

#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace koala {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service WifiManager. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class WifiManagerStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual WifiManager {
 public:
    ///Notifies all remote listeners about a change of value of the attribute wifiState.
    virtual void fireWifiStateAttributeChanged(const ::v1::com::koala::WifiManagerDataTypes::WifiState &wifiState) = 0;


    virtual void deactivateManagedInstances() = 0;

    void lockWifiStateAttribute(bool _lockAccess) {
        if (_lockAccess) {
            wifiStateMutex_.lock();
        } else {
            wifiStateMutex_.unlock();
        }
    }

protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
    std::recursive_mutex wifiStateMutex_;

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for WifiManager.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class WifiManagerStubRemoteEvent
{
public:
    virtual ~WifiManagerStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service WifiManager to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class WifiManagerStub
    : public virtual CommonAPI::Stub<WifiManagerStubAdapter, WifiManagerStubRemoteEvent>
{
public:
    typedef std::function<void ()> activeReply_t;

    virtual ~WifiManagerStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 2);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// Provides getter access to the attribute wifiState
    virtual const ::v1::com::koala::WifiManagerDataTypes::WifiState &getWifiStateAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireWifiStateAttributeChanged(::v1::com::koala::WifiManagerDataTypes::WifiState _value) {
    auto stubAdapter = CommonAPI::Stub<WifiManagerStubAdapter, WifiManagerStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireWifiStateAttributeChanged(_value);
    }
    void lockWifiStateAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<WifiManagerStubAdapter, WifiManagerStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockWifiStateAttribute(_lockAccess);
    }
    /// This is the method that will be called on remote calls on the method active.
    virtual void active(const std::shared_ptr<CommonAPI::ClientId> _client, WifiManagerDataTypes::WifiState _wifiState, activeReply_t _reply) = 0;


    using CommonAPI::Stub<WifiManagerStubAdapter, WifiManagerStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<WifiManagerStubAdapter, WifiManagerStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<WifiManagerStubAdapter, WifiManagerStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef WifiManagerStubRemoteEvent RemoteEventType;
    typedef ::v1::com::koala::WifiManager StubInterface;
};

} // namespace koala
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_KOALA_Wifi_Manager_STUB_HPP_
