/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/com/koala/WifiManagerSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace koala {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createWifiManagerSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< WifiManagerSomeIPProxy>(_address, _connection);
}

void initializeWifiManagerSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:com.koala.WifiManager:v1_0:wifi-manager",
        0x1234, 0x55f0, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "com.koala.WifiManager:v1_0",
        &createWifiManagerSomeIPProxy);
}

INITIALIZER(registerWifiManagerSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeWifiManagerSomeIPProxy);
}

WifiManagerSomeIPProxy::WifiManagerSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          wifiState_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x1b58), CommonAPI::SomeIP::event_id_t(0xea60), CommonAPI::SomeIP::method_id_t(0x2710), false, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, static_cast< ::v1::com::koala::WifiManagerDataTypes_::WifiStateDeployment_t* >(nullptr))
{
}

WifiManagerSomeIPProxy::~WifiManagerSomeIPProxy() {
}

WifiManagerSomeIPProxy::WifiStateAttribute& WifiManagerSomeIPProxy::getWifiStateAttribute() {
    return wifiState_;
}


void WifiManagerSomeIPProxy::active(WifiManagerDataTypes::WifiState _wifiState, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< WifiManagerDataTypes::WifiState, ::v1::com::koala::WifiManagerDataTypes_::WifiStateDeployment_t> deploy_wifiState(_wifiState, static_cast< ::v1::com::koala::WifiManagerDataTypes_::WifiStateDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                WifiManagerDataTypes::WifiState,
                ::v1::com::koala::WifiManagerDataTypes_::WifiStateDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x3e8),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_wifiState,
        _internalCallStatus);
}

std::future<CommonAPI::CallStatus> WifiManagerSomeIPProxy::activeAsync(const WifiManagerDataTypes::WifiState &_wifiState, ActiveAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< WifiManagerDataTypes::WifiState, ::v1::com::koala::WifiManagerDataTypes_::WifiStateDeployment_t> deploy_wifiState(_wifiState, static_cast< ::v1::com::koala::WifiManagerDataTypes_::WifiStateDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                WifiManagerDataTypes::WifiState,
                ::v1::com::koala::WifiManagerDataTypes_::WifiStateDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x3e8),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_wifiState,
        [_callback] (CommonAPI::CallStatus _internalCallStatus) {
            if (_callback)
                _callback(_internalCallStatus);
        },
        std::make_tuple());
}

void WifiManagerSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> WifiManagerSomeIPProxy::getCompletionFuture() {
    return CommonAPI::SomeIP::Proxy::getCompletionFuture();
}

} // namespace koala
} // namespace com
} // namespace v1
