/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_KOALA_Wifi_Manager_PROXY_HPP_
#define V1_COM_KOALA_Wifi_Manager_PROXY_HPP_

#include <v1/com/koala/WifiManagerProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace koala {

template <typename ... _AttributeExtensions>
class WifiManagerProxy
    : virtual public WifiManager,
      virtual public WifiManagerProxyBase,
      virtual public _AttributeExtensions... {
public:
    WifiManagerProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~WifiManagerProxy();

    typedef ::v1::com::koala::WifiManager InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Returns the wrapper class that provides access to the attribute wifiState.
     */
    virtual WifiStateAttribute& getWifiStateAttribute() {
        return delegate_->getWifiStateAttribute();
    }
    /**
     * Calls active with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void active(WifiManagerDataTypes::WifiState _wifiState, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls active with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> activeAsync(const WifiManagerDataTypes::WifiState &_wifiState, ActiveAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);



 private:
    std::shared_ptr< WifiManagerProxyBase> delegate_;
};

typedef WifiManagerProxy<> WifiManagerProxyDefault;

namespace WifiManagerExtensions {
    template <template <typename > class _ExtensionType>
    class WifiStateAttributeExtension {
     public:
        typedef _ExtensionType< WifiManagerProxyBase::WifiStateAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< WifiManagerProxyBase::WifiStateAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        WifiStateAttributeExtension(WifiManagerProxyBase& proxy): attributeExtension_(proxy.getWifiStateAttribute()) {
        }
    
        inline extension_type& getWifiStateAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace WifiManagerExtensions

//
// WifiManagerProxy Implementation
//
template <typename ... _AttributeExtensions>
WifiManagerProxy<_AttributeExtensions...>::WifiManagerProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< WifiManagerProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< WifiManagerProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
WifiManagerProxy<_AttributeExtensions...>::~WifiManagerProxy() {
}

template <typename ... _AttributeExtensions>
void WifiManagerProxy<_AttributeExtensions...>::active(WifiManagerDataTypes::WifiState _wifiState, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    if (!_wifiState.validate()) {
        _internalCallStatus = CommonAPI::CallStatus::INVALID_VALUE;
        return;
    }
    delegate_->active(_wifiState, _internalCallStatus, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> WifiManagerProxy<_AttributeExtensions...>::activeAsync(const WifiManagerDataTypes::WifiState &_wifiState, ActiveAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    if (!_wifiState.validate()) {
        _callback(CommonAPI::CallStatus::INVALID_VALUE);
        std::promise<CommonAPI::CallStatus> promise;
        promise.set_value(CommonAPI::CallStatus::INVALID_VALUE);
        return promise.get_future();
    }
    return delegate_->activeAsync(_wifiState, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &WifiManagerProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool WifiManagerProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool WifiManagerProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& WifiManagerProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& WifiManagerProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> WifiManagerProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace koala
} // namespace com
} // namespace v1

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v1::com::koala::WifiManagerProxy,
    _AttributeExtension> {
    typedef typename ::v1::com::koala::WifiManagerProxy<
            ::v1::com::koala::WifiManagerExtensions::WifiStateAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_KOALA_Wifi_Manager_PROXY_HPP_
