/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_KOALA_Wifi_Manager_STUB_DEFAULT_HPP_
#define V1_COM_KOALA_Wifi_Manager_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/com/koala/WifiManagerStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace com {
namespace koala {

/**
 * Provides a default implementation for WifiManagerStubRemoteEvent and
 * WifiManagerStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT WifiManagerStubDefault
    : public virtual WifiManagerStub {
public:
    COMMONAPI_EXPORT WifiManagerStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(WifiManager::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT WifiManagerStubRemoteEvent* initStubAdapter(const std::shared_ptr< WifiManagerStubAdapter> &_adapter) {
        CommonAPI::Stub<WifiManagerStubAdapter, WifiManagerStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual const ::v1::com::koala::WifiManagerDataTypes::WifiState &getWifiStateAttribute() {
        return wifiStateAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const ::v1::com::koala::WifiManagerDataTypes::WifiState &getWifiStateAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getWifiStateAttribute();
    }
    COMMONAPI_EXPORT virtual void setWifiStateAttribute(::v1::com::koala::WifiManagerDataTypes::WifiState _value) {
        const bool valueChanged = trySetWifiStateAttribute(std::move(_value));
        if (valueChanged) {
            fireWifiStateAttributeChanged(wifiStateAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void active(const std::shared_ptr<CommonAPI::ClientId> _client, WifiManagerDataTypes::WifiState _wifiState, activeReply_t _reply) {
        (void)_client;
        (void)_wifiState;
        _reply();
    }


protected:
    COMMONAPI_EXPORT virtual bool trySetWifiStateAttribute(::v1::com::koala::WifiManagerDataTypes::WifiState _value) {
        if (!validateWifiStateAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<WifiManagerStubAdapter> stubAdapter = CommonAPI::Stub<WifiManagerStubAdapter, WifiManagerStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockWifiStateAttribute(true);
            valueChanged = (wifiStateAttributeValue_ != _value);
            wifiStateAttributeValue_ = std::move(_value);
            stubAdapter->lockWifiStateAttribute(false);
        } else {
            valueChanged = (wifiStateAttributeValue_ != _value);
            wifiStateAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateWifiStateAttributeRequestedValue(const ::v1::com::koala::WifiManagerDataTypes::WifiState &_value) {
        (void)_value;
        return _value.validate();
    }
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual WifiManagerStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(WifiManagerStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        WifiManagerStubDefault *defaultStub_;
    };
protected:
    WifiManagerStubDefault::RemoteEventHandler remoteEventHandler_;

private:

    ::v1::com::koala::WifiManagerDataTypes::WifiState wifiStateAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace koala
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_KOALA_Wifi_Manager_STUB_DEFAULT
