/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COM_KOALA_WIFI_MANAGER_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COM_KOALA_WIFI_MANAGER_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/com/koala/WifiManagerStub.hpp>
#include <v1/com/koala/WifiManagerDataTypesSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace koala {

template <typename _Stub = ::v1::com::koala::WifiManagerStub, typename... _Stubs>
class WifiManagerSomeIPStubAdapterInternal
    : public virtual WifiManagerStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< WifiManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> WifiManagerSomeIPStubAdapterHelper;

    ~WifiManagerSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        WifiManagerSomeIPStubAdapterHelper::deinit();
    }

    void fireWifiStateAttributeChanged(const ::v1::com::koala::WifiManagerDataTypes::WifiState &_value);
    
    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::com::koala::WifiManagerStub,
        CommonAPI::Version
    > getWifiManagerInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::com::koala::WifiManagerStub,
        ::v1::com::koala::WifiManagerDataTypes::WifiState,
        ::v1::com::koala::WifiManagerDataTypes_::WifiStateDeployment_t
    > getWifiStateAttributeStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::com::koala::WifiManagerStub,
        std::tuple< WifiManagerDataTypes::WifiState>,
        std::tuple< >,
        std::tuple< ::v1::com::koala::WifiManagerDataTypes_::WifiStateDeployment_t>,
        std::tuple< >
    > activeStubDispatcher;
    
    WifiManagerSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        WifiManagerSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< WifiManagerStub>(_stub)),
        getWifiManagerInterfaceVersionStubDispatcher(&WifiManagerStub::lockInterfaceVersionAttribute, &WifiManagerStub::getInterfaceVersion, false, true),
        getWifiStateAttributeStubDispatcher(
            &::v1::com::koala::WifiManagerStub::lockWifiStateAttribute,
            &::v1::com::koala::WifiManagerStub::getWifiStateAttribute,
            false,
            _stub->hasElement(0))
        ,
        activeStubDispatcher(
            &WifiManagerStub::active,
            false,
            _stub->hasElement(1),
            std::make_tuple(static_cast< ::v1::com::koala::WifiManagerDataTypes_::WifiStateDeployment_t* >(nullptr)),
            std::make_tuple())
        
    {
        WifiManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2710) }, &getWifiStateAttributeStubDispatcher );
        WifiManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x3e8) }, &activeStubDispatcher );
        std::shared_ptr<CommonAPI::SomeIP::ClientId> itsClient = std::make_shared<CommonAPI::SomeIP::ClientId>();

        // Provided events/fields
        if (_stub->hasElement(0)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x1b58)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xea60), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireWifiStateAttributeChanged(std::dynamic_pointer_cast< ::v1::com::koala::WifiManagerStub>(_stub)->getWifiStateAttribute(itsClient));
        }

    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void WifiManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireWifiStateAttributeChanged(const ::v1::com::koala::WifiManagerDataTypes::WifiState &_value) {
    CommonAPI::Deployable< ::v1::com::koala::WifiManagerDataTypes::WifiState, ::v1::com::koala::WifiManagerDataTypes_::WifiStateDeployment_t> deployedValue(_value, static_cast< ::v1::com::koala::WifiManagerDataTypes_::WifiStateDeployment_t* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::v1::com::koala::WifiManagerDataTypes::WifiState,
                ::v1::com::koala::WifiManagerDataTypes_::WifiStateDeployment_t
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xea60),
        false,
        deployedValue
    );
}


template <typename _Stub, typename... _Stubs>
void WifiManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void WifiManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v1::com::koala::WifiManagerStub, typename... _Stubs>
class WifiManagerSomeIPStubAdapter
    : public WifiManagerSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    WifiManagerSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          WifiManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace koala
} // namespace com
} // namespace v1

#endif // V1_COM_KOALA_Wifi_Manager_SOMEIP_STUB_ADAPTER_HPP_
