/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_KOALA_Wifi_Manager_Data_Types_HPP_
#define V1_COM_KOALA_Wifi_Manager_Data_Types_HPP_



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace koala {

struct WifiManagerDataTypes {
    
    struct WifiState : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            ON = 0,
            OFF = 1
        };
    
        WifiState()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::ON)) {}
        WifiState(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::ON):
                case static_cast< uint8_t>(Literal::OFF):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const WifiState &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const WifiState &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const WifiState &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const WifiState &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const WifiState &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const WifiState &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::ON): return "ON";
            case static_cast< uint8_t>(Literal::OFF): return "OFF";
            default: return "UNDEFINED";
            }
        }
    };


static inline const char* getTypeCollectionName() {
    static const char* typeCollectionName = "com.koala.WifiManagerDataTypes";
    return typeCollectionName;
}

inline CommonAPI::Version getTypeCollectionVersion() {
    return CommonAPI::Version(1, 0);
}

}; // struct WifiManagerDataTypes

} // namespace koala
} // namespace com
} // namespace v1

namespace CommonAPI {
}


namespace std {
    //Hash for WifiState
    template<>
    struct hash< ::v1::com::koala::WifiManagerDataTypes::WifiState> {
        inline size_t operator()(const ::v1::com::koala::WifiManagerDataTypes::WifiState& wifiState) const {
            return static_cast< uint8_t>(wifiState);
        }
    };
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_KOALA_Wifi_Manager_Data_Types_HPP_
