KOALA_DLT_VERSION = v2.18.10
KOALA_DLT_SITE = $(call github,COVESA,dlt-daemon,$(KOALA_DLT_VERSION))
KOALA_DLT_LICENSE = MIT
KOALA_DLT_LICENSE_FILES = LICENSE
KOALA_DLT_DEPENDENCIES = zlib

KOALA_DLT_INSTALL_STAGING = YES
KOALA_DLT_INSTALL_TARGET = YES

#KOALA_DLT_CONF_OPTS +=  -DCMAKE_PREFIX_PATH=$(STAGING_DIR)/usr

$(eval $(cmake-package))
